### PR TITLE
Template restructure

### PR DESCRIPTION
**Pull request by adamk5550**
Added a template for others to contribute. 

Also changed the structure @adamkelsall  have a check over before i change this across the repo.

### CODE REVIEW

**Comment by adamkelsall** [comment]
Good start, I'm liking the emojis! :sparkles:

I'm wondering if we can refine this further; instead of categorising things by their format (article, presentation etc.), we actually categorise them by the sort of information they convey, and use emojis to *colour code* them by format.

Examples:

- Documentation
- Guides
- Opinion Pieces

Thoughts?

**Comment by adamkelsall** [comment]
Also we can make a `CONTRIBUTING.md` file to specify guidelines, perhaps including the template: https://github.com/blog/1184-contributing-guidelines

**Comment by adamkelsall** [comment]
Suggested emojis and their meanings:

- :movie_camera: video
- :bar_chart: presentation
- :page_facing_up: article
- :pound: paid for content

WIP - will be editing this again later with more.

**Comment by adamkelsall** [comment]
I've had a proper sit down with this now and bashed the whole thing out. I've separated guidance on how to contribute and the format we've got things in, to `CONTRIBUTING.md`, and kept the template separate in `template.md`.

I've settled on the emoji "labels", which have been documented in `README.md`.

My only issue at the moment is I'm not happy with the lack of difference between the *Design Patterns* and *Ways of Working* sections - check the template for my write-ups on what they are. I feel like they're not the same, but can't think of good enough titles to express this. Thoughts?

Beyond that, let me know what you think overall. Once we're happy, we can start going through and changing all the pages :cold_sweat:

**Comment by adamkelsall** [comment]
@adamk5550 done :raised_hands:

**Comment by adamk5550** [comment]
I would approve, but i opened the PR 😢

**Pull request merged**
